### ISSUE TITLE
GBSX quality cutoff

### ISSUE THREAD

**Issue by MBCSD** [GenomicsCoreLeuven/GBSX#1]
Hi,

I'm using GBSX demultiplexer and it works great.  Thanks so much for this really nice script.  But I'm loosing a lot of samples because their average quality seems to be just a little bit low.  It the quality cutoff hardcoded in the script?  Is there any way to adjust it?

Thanks so much,
Molly

**Comment by MBCSD** [comment]
Still looking for a way to lower the quality threshold.  Anyone have any idea?

Thanks..

**Comment by KoenHerten** [comment]
Hi Molly,

Sorry for the late answer, but i have been sick for a long time.
I did not implement a quality cutoff. This because there are many other scripts that does this. If you think there is, you can always show an example, and I will try to figure out what cause this, for you, unwanted behaviour.

Cheers,
Koen

**Comment by MBCSD** [comment]
HI Koen,

Thanks so much for getting back to me.  I’m sorry you’ve been sick.  I hope you are feeling better.  It looks like we were running into this problem just for that first run.  Your script works fine for us now.  Thanks so much for making your work available.  It’s been very useful.

Best,
Molly Dunn

Molly Dunn
Crop Genetics

[cid:image002.png@01CE5C41.9EAB9E40]
