### ISSUE TITLE
Error message in GBSX demultiplexing

### ISSUE THREAD

**Issue by alexiou1977** [GenomicsCoreLeuven/GBSX#2]
When I run GBSX demultiplexer with the example data, the tool works correctly. But when I launch the tool with my data I get the following error:

---

Start the demultiplexing.
USE DUAL BARCODING: false
GBS demultiplexing ended with Major Errors

---

The command is the following:
java -jar ~/local/software/GBSX/releases/latest/GBSX_v1.1.4.jar --Demultiplexer -f1 AF17FXXXX_1_9_GATCAG_L001_R1_001.fastq.gz -f2 AF17FXXXX_1_9_GATCAG_L001_R2_001.fastq.gz -i ApekI_info_file.txt -o ApekI_dimultiplexed -n false -gzip true

ApekI_info_file.txt:
AB0312  CCGGATAGTAAT    ApekI   GATCAG
AB0313  TAACGA  ApekI   GATCAG
AB0314  CGGTAGA ApekI   GATCAG
AB0315  CTTCCA  ApekI   GATCAG
AB0316  GAATTCAT    ApekI   GATCAG
AB0317  AACGCCT ApekI   GATCAG

output of the gbsDemultiplex.log:

---

Arguments where: [Ljava.lang.String;@5affce21

String index out of range: 140Ended on Tue Nov 17 14:53:35 CET 2015

---

Any advice it would be appreciated!

**Comment by jaholliday** [comment]
I am getting the same issue and error messages. The only difference with the above is my data is not GBS (no enzyme hence NAN in the enzyme column) and I have five base pair barcodes.
Thanks for any advice you can give.

**Comment by KoenHerten** [comment]
Hi,
You must now that the tool demultiplexes both GBS and RAD data. The traditional GBS protocol discribes an enzyme at both ends, while the traditional RAD protocol only have an enzyme at the end of the barcode. Since no enzyme (NAN) is actually more an exception of the RAD protocol (since the other end already has no enzyme), you should run it as a RAD protocol.
So you should add the option -rad true.
Cheers,
Koen

**Comment by jaholliday** [comment]
Thanks so much Koen. I’ll try that tomorrow. I was having a hard time finding something to demultiplex the inline barcodes in data from our custom RNA-seq library prep method, and your tool was one of the few that appeared to do this without requiring a restriction site be present (like Stacks).

Cheers,

## Jason

Jason Holliday
Associate Professor
Department of Forest Resources and Environmental Conservation
Virginia Tech
304 Cheatham Hall
Office: 540 231 7267
Cell: 540 558 8078

On Mar 29, 2016, at 3:43 PM, Koen Herten <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
You must now that the tool demultiplexes both GBS and RAD data. The traditional GBS protocol discribes an enzyme at both ends, while the traditional RAD protocol only have an enzyme at the end of the barcode. Since no enzyme (NAN) is actually more an exception of the RAD protocol (since the other end already has no enzyme), you should run it as a RAD protocol.
So you should add the option -rad true.
Cheers,
Koen
