### ISSUE TITLE
String index out of range: error

### ISSUE THREAD

**Issue by MBCSD** [GenomicsCoreLeuven/GBSX#5]
HI,

I've been using your demultiplexer and most of the time it works great but sometime it crashes.  The error in the log file says:

Arguments where: [Ljava.lang.String;@64fd5bdf

String index out of range: 66Ended on Thu Mar 31 12:53:46 EDT 2016

I've looked at all of my inputs and can't find anything wrong.  Do you have any thought on what this error might mean?

Thanks again for making this software available.
Molly

**Comment by MBCSD** [comment]
Sorry I just realized that there was another comment with the same issue I'm having.  But my data is more like traditional GBS data.  

This is my command and a few lines of the input file.

 java -jar /tools/bioinfo/app/gbsx-1.1.4/releases/latest/GBSX_v1.1.4.jar --Demultiplexer -f1 ALL_R1.fastq -f2 ALL_R2.fastq -i BarCodeFile.txt -s 3 -me 0 -mb 0 -ca AGATCGGAAGAGCG -kc false

BarCodeFile.txt File:
0MRS41FS180    TTCAAC  HindIII NlaIII
10MRS41FS181    ATGCCT  HindIII NlaIII
10MRS41FS192    ATATGT  HindIII NlaIII
10MRS41FS193    CATCGT  HindIII NlaIII
10MRS41FS195    CGCGGT  HindIII NlaIII

The program will parsed about 2/3 of the reads and then die.  So it doesn't error out right away.

Thanks again.

**Comment by KoenHerten** [comment]
Hi Molly,

I'm on holliday, so this is a quick answer, but I think that HindIII and NIaIII are not in the known enzyme list, and you do not add it. This way, the program will act as it has the NAN enzyme (no enzyme) (I will change this in the next update). As long the reads does not have to be trimmed, the program will work perfect. But when a read has to be trimmed, the error will occure (that is why the NAN has to work with the -rad option). You can solve this problem using the -ea or -er option. If you want I can  include these enzymes in the next update.

Cheers,
Koen

**Comment by MBCSD** [comment]
Hi Koen,

Thanks so much for your really quick answer.  I'm sorry I was bugging you while you are on vacation.  No need to rush for this answer...:)

So I ran the command like this:

java -jar /tools/bioinfo/app/gbsx-1.1.4/releases/latest/GBSX_v1.1.4.jar --Demultiplexer -f1 ALL_R1.fastq -f2 ALL_R2.fastq -i BarCodeFile.txt -s 3 -me 0 -mb 0 -ca AGATCGGAAGAGCG -kc false -er HindIII_NlaIII.txt 

Still the same problem.

It demultiplexes about 125 million reads out of 300Million and then dies.

I've changed -s to 2 and -me and -mb to 1 and it still dies.  Although not always at the same place.  Could it be memory?

Should I try one of the other algorithms?

Thanks again!

**Comment by estolle** [comment]
Hi there

I think i am having the same problem. I am running GBSX 1.1.4 and also tried 1.1.5 and 1.2 with the same result. 
gbs log says:
Arguments where: [Ljava.lang.String;@3303d939
String index out of range: 273Ended on Mon Apr 18 14:42:02 BST 2016
Along with the error message, it seems to screw something with the demultiplexing up as resulting R1 and R2 have often different filesizes/line count - always the R2 output is larger than the R1 output.

I once tried to narrow the problem down and found one read pair causing it to fail. However, the readpair (with its barcodes/adapters etc) looks perfectly normal to me. I then got it running my setting me to 0 and mb to 0. 

But now (different subset of the data), i have the problem again and no clue what the cause is. 

Another note/info. I had some problems earlier, when the sample names (for the barcode combinations) contained special characters or (in this case) portugues letters like the "ã" as in São Paulo (same with n and others).

Another thing which is possibly related to the problem above:
I am supplying a custom sequence as restriction enzyme. It seems the enzyme site does not get trimmed off from all reads (reverse reads) although I put the setting "-kc false"

my command was:
java -jar GBSX_v1.2.jar --Demultiplexer -i barcodes.tsv.gbsx -er linkers3.tsv -kc false -mb 0 -me 0 -gzip false -f1 reads_S1_L001_R1_001.fastq -f2 reads_S1_L001_R2_001.fastq -o /results/

my java version on the cluster i am using
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by estolle** [comment]
short update: this time it seems to run through if I leave out the "-kc false" option. I think I can trim this off afterwards.
Would it maybe be possible that the error related to the provided enzyme site could arise if GBSX finds it twice within close proximity?

**Comment by el42008** [comment]
Hi, 

I am trying to demultiplex 3 GBS pools that have been cut with 2 enzymes. I just add in teh barcode list.txt file name of sample barcode and enzyme1, and just one pool is being demultiplexed. For the other two I get this message:

Start the demultiplexing.
USE DUAL BARCODING: false
GBS demultiplexing ended with Major Errors

Should I include the common adapter with the enzyme?

Cheers

**Comment by KoenHerten** [comment]
Hi estolle,

I could not replicate your error. However I think that keeping the restriction site is better then removing. This because the restriction site is part of the actual DNA fragment, and not added later. Second the extra information in the reads will increase the mapping quality for smaller fragements.

Cheers

**Comment by KoenHerten** [comment]
Hi el42008,

Since 1 pool is being demultiplexed, your parameters will be correct. My first gues for the other 2 pools would be that the original fastq files are corrupt. Can you check if both files contain the same number of lines, and if that number can be devided by 4?

Cheers

**Comment by KoenHerten** [comment]
Closed issue, because no feed-back on the latest proposed solution
